# Copyright (c) 2020-2023 Pcap Project
# SPDX-License-Identifier: MIT OR Apache-2.0

name: Bug Report
description: File a bug report
title: "[BUG] "
labels: ["bug"]
assignees: ardikars

body:
 - type: markdown
   attributes:
    value: |
     Please fill out a clear and concise description of what the bug is. (If what you are experiencing is NOT a bug but instead a support issue, please open a Discussion instead!)
 - type: textarea
   id: what-happened
   attributes:
    label: What happened?
    description: A clear and concise description of what happened, how to reproduce it, and what you expected to happen.
   validations:
    required: true
 - type: input
   id: version-java
   attributes:
    label: Version (Java)
    description: What version of Pcap Java Library are you running?
   validations:
    required: true
 - type: input
   id: version-c
   attributes:
    label: Version (Native library, e.g. Libpcap/Npcap)
    description: What version of Libpcap/Npcap are you running?
   validations:
    required: true
 - type: dropdown
   id: platform
   attributes:
    label: What platform are you using?
    multiple: false
    options:
     - Windows
     - macOS
     - Linux
     - BSD
 - type: textarea
   id: logs
   attributes:
    label: Relevant log output
    description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
    render: shell