# Copyright (c) 2020-2023 Pcap Project
# SPDX-License-Identifier: MIT OR Apache-2.0

contact_links:
  - about: Ask a question or request support here
    name: Ask for Support
    url: >-
      https://github.com/ardikars/pcap/discussions/new